### ISSUE TITLE
Make the output copiable

### ISSUE THREAD

**Issue by Bhasmithal** [tomscript/babbage#5]
It is impossible to copy the output of the tool after an encoding/decoding (for example), and that pretty much makes it useless for any "quick an dirty" conversion on the fly. It would be extremely useful if it was possible to copy the output so I don't have to download a file each time, open it in my text editor, and THEN copy the result.

**Comment by balidani** [comment]
^

**Comment by tomscript** [comment]
Thanks for fixing in #6 . https://babbage-stable.appspot.com/ is now updated.
